### ISSUE TITLE
[Bug] The app crashes when playing music, and the screen becomes unresponsive.

### ISSUE THREAD

**Issue by yuxigu5254** [TJYSunset/Phocid#173]
The app crashes when playing music, and the screen becomes unresponsive. System: MIUI14 Android 13. 

[crash.txt](https://github.com/user-attachments/files/22398616/crash.txt)

**Comment by yuxigu5254** [comment]
> You can check out [code changes in that version](https://github.com/TJYSunset/Phocid/compare/v20250617...v20250617.1) yourself:
> 
> * Modified version number
> * Removed two math operations from UI code
> * Modified some strings
> 
> These obviously can't crash a normal system. Although your effort to help is appreciated, I don't think that should have anything to do with Phocid; You might want to try upgrading your system first, or undo system modifications if you've made any.

Hello, I haven't made any modifications to the system. The music players I have used, such as Salt Player, Poweramp, Musicolet, Oto Music, LMusic, Gramophone, Flamingo, Music-Player, Light Cone Music, Cotton Music etc., have never crashed. I am almost certain that Phocid started crashing from v20250617.1. It will crash when both of the following two conditions are met: ① Music is being played; ② The screen is swiped. v20250617 doesn't crash, and I am using this version now. However, after v20250617.1, almost every time I swipe the screen while playing music, the screen becomes unresponsive. This can only be resolved in two ways: either wait for the current song to finish playing (a crash toast will pop up afterward), or let the screen turn off automatically (which pauses the currently playing song) – then I can turn the screen back on and swipe Phocid away from the background. In severe cases, a phone restart is required.

**Comment by yuxigu5254** [comment]
> You can check out [code changes in that version](https://github.com/TJYSunset/Phocid/compare/v20250617...v20250617.1) yourself:
> 
> * Modified version number
> * Removed two math operations from UI code
> * Modified some strings
> 
> These obviously can't crash a normal system. Although your effort to help is appreciated, I don't think that should have anything to do with Phocid; You might want to try upgrading your system first, or undo system modifications if you've made any.

Sorry, right after replying, I opened Phocid and used it normally for a while, but it crashed again. I think I need to test more versions, but this issue must be related to Phocid—because I have used many music players before, and this is the first time such a situation has occurred.

**Comment by TJYSunset** [comment]
Even if there is a bug in Phocid, your system also should not crash because of a non-privileged app under any circumstances, so there's still a problem with your system.

> System: MIUI14 Android 13.

Android 13 was released three years ago. It's probably expected that you can encounter weird bugs that have been fixed by Xiaomi since then.

**Comment by yuxigu5254** [comment]
> Even if there is a bug in Phocid, your system also should not crash because of a non-privileged app under any circumstances, so there's still a problem with your system.
> 
> > System: MIUI14 Android 13.
> 
> Android 13 was released three years ago. It's probably expected that you can encounter weird bugs that have been fixed by Xiaomi since then.

Could you please take another look at this new crash log? The only thing I can be sure of right now is that it only crashes when playing music, and it won't crash when not playing music.

[crash (1).txt](https://github.com/user-attachments/files/22437468/crash.1.txt)

**Comment by TJYSunset** [comment]
It's still `DeadSystemException`.

I could only find this [remotely related StackOverflow question](https://stackoverflow.com/q/75643090) mentioning requiring the `ACCESS_NETWORK_STATE` permission which I patched out; Here's a build that reintroduces that permission.

[app-release.zip](https://github.com/user-attachments/files/22439404/app-release.zip)

There's nothing more I can do to fix a system crash.

**Comment by yuxigu5254** [comment]
> It's still `DeadSystemException`.
> 
> I could only find this [remotely related StackOverflow question](https://stackoverflow.com/q/75643090) mentioning requiring the `ACCESS_NETWORK_STATE` permission which I patched out; Here's a build that reintroduces that permission.
> 
> [app-release.zip](https://github.com/user-attachments/files/22439404/app-release.zip)
> 
> There's nothing more I can do to fix a system crash.

Thank you very much for the fix, but unfortunately, it still crashes. I'm very happy to experience the software you developed—it is currently the only local player I can find that supports all the following functions:
① Custom folders
② Custom separators + split whitelists
③ Sort by the number of tracks
④ Support for Chinese sorting
⑤ The artist page supports sorting by year (there is a small drawback regarding this: the secondary sorting when sorting by year is not based on album name + disc number and track number)
 
I think I will continue to use your software if I change my phone in the future. Thank you for your efforts.
